const menu = [
  {
    id: 1,
    title: "Mediterranean Breakfast",
    category: "breakfast",
    price: 15.5,
    img: "./images/id1.jpg",
    desc: `Two free range scrambled eggs, feta cheese, muska boregi, halloumi cheese, Turkish beef sausage, tomatoes, cucumber, rocket, olives, simit circular bread, butter, honey and jam `,
  },
  {
    id: 2,
    title: "Sucuk Yumurta",
    category: "breakfast",
    price: 11.5,
    img: "./images/id2.jpg",
    desc: `Grilled turkish beef sausage served with eggs `,
  },
  {
    id: 3,
    title: "Vegan Breakfast",
    category: "breakfast",
    price: 14.5,
    img: "./images/id3.jpg",
    desc: `Crushed avocado, mushrooms, hash brown, grilled tomato, beans, vegan sausage and salad `,
  },
  {
    id: 4,
    title: "Humus",
    category: "meze",
    price: 6.9,
    img: "./images/id4.jpg",
    desc: `Chickpea puree with tahini, garlic and olive oil `,
  },
  {
    id: 5,
    title: "Tabouleh",
    category: "meze",
    price: 7.5,
    img: "./images/id5.jpg",
    desc: `Bulgur, parsley, fresh mint, pomegranate, red onion `,
  },
  {
    id: 6,
    title: "Fried Calamari",
    category: "meze",
    price: 8.9,
    img: "./images/id6.jpg",
    desc: `Calamari coated with breadcrumbs, cream, egg, flour `,
  },
  {
    id: 7,
    title: "Mantarli Hellim",
    category: "meze",
    price: 8.99,
    img: "./images/id7.jpg",
    desc: `Grilled mushrooms and Halloumi cheese, parsley `,
  },
  {
    id: 8,
    title: "Tavuk Pide",
    category: "dinner",
    price: 15.45,
    img: "./images/id8.jpg",
    desc: `Chicken, red and green peppers, parsley and mozzarella `,
  },
  {
    id: 9,
    title: "Ispanak Pide",
    category: "dinner",
    price: 16.99,
    img: "./images/id9.jpg",
    desc: `Spinach, feta cheese, red peppers, onions and mozzarella `,
  },
  {
    id: 10,
    title: "Sea Bass",
    category: "dinner",
    price: 21.5,
    img: "./images/id10.jpg",
    desc: `Chargrilled seabass served with baby potatoes and salad `,
  },
  {
    id: 11,
    title: "Lamb Döner",
    category: "dinner",
    price: 19.5,
    img: "./images/id11.jpg",
    desc: `Succulent pieces of lamb, layered on one huge skewer and then slow cooked for maximum tongue bursting flavours `,
  },
  {
    id: 12,
    title: "Chicken Shish",
    category: "dinner",
    price: 20.5,
    img: "./images/id12.jpg",
    desc: `Lean chunks of chicken skewered and grilled over charcoal `,
  },
  {
    id: 13,
    title: "Adana Kebab",
    category: "dinner",
    price: 20.45,
    img: "./images/id13.jpg",
    desc: `Seasoned minced lamb skewered and grilled over charcoal `,
  },
  {
    id: 14,
    title: "Ali Nazik",
    category: "dinner",
    price: 19.6,
    img: "./images/id14.jpg",
    desc: `Chargrilled aubergines, garlic, tahin, yogurt, lamb shish `,
  },
  {
    id: 15,
    title: "Sarma Tavuk Beyti",
    category: "dinner",
    price: 20.45,
    img: "./images/id15.jpg",
    desc: `Seasoned mince chicken grilled over charcoal, wrapped in lavash bread and mozzarella, topped with tomato sauce and butter, served with yogurt and bulgur `,
  },
  {
    id: 16,
    title: "Baklava",
    category: "desserts",
    price: 6.5,
    img: "./images/id16.jpg",
    desc: `Golden brown fillo dough, with a thick middle layer of crushed pistachio nuts, topped with syrup, finished with a sprinkle of pistachios and served with vanilla ice cream `,
  },
  {
    id: 17,
    title: "Künefe",
    category: "desserts",
    price: 7.5,
    img: "./images/id17.jpg",
    desc: `Künefe is a grilled dessert made from two layers of crispy phyllo dough filled with cheese and syrup and finished with a sprinkle of pistachios `,
  },
  {
    id: 18,
    title: "Sütlaç",
    category: "desserts",
    price: 4.5,
    img: "./images/id18.jpg",
    desc: `Rice pudding seved with cinnamon and vanilla sugar `,
  },
  {
    id: 19,
    title: "Lemon & Mascarpone Cheesecake",
    category: "desserts",
    price: 5.5,
    img: "./images/id19.jpg",
    desc: `A crisp digestive biscuit base topped with a lemon and mascarpone cheesecake, decorated with a smooth lemon curd cream scattered with roasted flaked almonds `,
  },
  {
    id: 20,
    title: "Le Coste Trebbiano di Romagna - Emilia Romagna, Italy",
    category: "drinks",
    price: 8.0,
    img: "./images/id20.jpg",
    desc: `Refreshing and light-bodied with citrus flavours and delicate perfumed notes `,
  },
  {
    id: 21,
    title: "La Serre Chardonnay - Pays d’Oc, France",
    category: "drinks",
    price: 8.5,
    img: "./images/id21.jpg",
    desc: `This light and refreshing Chardonnay has aromas and flavours of lemons and crisp green apples. `,
  },
  {
    id: 22,
    title:
      "Santa Rita Gran Hacienda Sauvignon Blanc - Casablanca Valley, Chile",
    category: "drinks",
    price: 9.45,
    img: "./images/id22.jpg",
    desc: `A fragrant blend of citrus fruit and passion fruit with a slightly herbal backdrop. On the palate, it is concentrated, with a pleasant acidity that highlights its freshness `,
  },
  {
    id: 23,
    title: "Vaporetto Prosecco NV - Veneto, Italy",
    category: "drinks",
    price: 11.45,
    img: "./images/id23.jpg",
    desc: `Straw yellow with lightly green hints. It is a fine and persistent wine. It has flavours and aromas of fruity apple, with light hints of apricot and citrus `,
  },
];
export default menu;
